;------------------------------------------------------------------------------
; Filename: mfunc6.mac
; corbin dunn / corbin@corbinsworkshop.com
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

g65 "\cncm\CorbinsWorkshop\mfunc6_corbin.mac"

N1000

