+ =======================================
+ ---
+ Version 1
+   + Eric Schimelpfenig, Avid CNC
+  + corbin dunn, added G43 call after M6 in two locations!
+ =======================================


POST_NAME = "Avid EX Control ATC (Inch) (*.cnc)"

FILE_EXTENSION = "cnc"

UNITS = "INCHES"

LASER_SUPPORT = "YES"
+------------------------------------------------
+    Line terminating characters
+------------------------------------------------

LINE_ENDING = "[13][10]"

+------------------------------------------------
+    Block numbering
+------------------------------------------------

LINE_NUMBER_START = 10
LINE_NUMBER_INCREMENT = 10
LINE_NUMBER_MAXIMUM = 999999

+================================================
+
+    Formating for variables
+
+================================================

VAR LINE_NUMBER = [N|A|N|04.0]
VAR SPINDLE_SPEED = [S|A| S|1.0]
VAR FEED_RATE = [F|C| F|1.0]
VAR X_POSITION = [X|C| X|1.4]
VAR Y_POSITION = [Y|C| Y|1.4]
VAR Z_POSITION = [Z|C| Z|1.4]
VAR X_HOME_POSITION = [XH|A| X|1.4]
VAR Y_HOME_POSITION = [YH|A| Y|1.4]
VAR Z_HOME_POSITION = [ZH|A| Z|1.4]
VAR ARC_CENTRE_I_INC_POSITION = [I|A| I|1.4]
VAR ARC_CENTRE_J_INC_POSITION = [J|A| J|1.4]
VAR DWELL_TIME = [DWELL|A|P|1.2]


+================================================
+
+    Block definitions for toolpath output
+
+================================================

+---------------------------------------------------
+  Commands output at the start of the file
+---------------------------------------------------

begin HEADER

"[N] ; ---------------------------------------------"
"[N] ; Filename: [TOOLPATH_NAME]"
"[N] ;XY Origin Position[XY_ORIGIN]"
"[N] ;XY Origin Value X[X_ORIGIN_POS] Y[Y_ORIGIN_POS]"
"[N] ;Z Origin [Z_ORIGIN]"
"[N] ;"
"[N] ;Material size:"
"[N] ;X [XLENGTH] Y [YLENGTH] Z [ZLENGTH]"
"[N] ;"
"[N] ;Tools Used In Job:"
"[N] ;[TOOLS_USED]"
"[N] ;"
"[N] ;Toolpaths In this Job"
"[N] ;[TOOLPATHS_OUTPUT]"
"[N] ;"
"[N] ; Generated by Vectric for Avid EX Controllers"
"[N] ; ---------------------------------------------"
"[N] ; Move to Z home "
"[N] G53 Z0"
"[N] ; Circular Interpolation Plane Selection XY - Cutter Compensation Cancel"
"[N] G17 G40"
"[N] ; Select Inches Units"
"[N] G20"
"[N] ; Canned Cycle Cancel"
"[N] G80"
"[N] ; Absolute Positioning Mode"
"[N] G90"

"[N] ; ---------------------------------------------"
"[N] ; Toolchange: T[T] - Speed:[S]"
"[N] ; ---------------------------------------------"
"[N] ; Start Tool Change"
"[N] T[T] M6"
"[N] G43 H[T]"
"[N] ; Spindle on CW"
"[N] M3 [S][F]"
"[N] ; ---------------------------------------------"


+---------------------------------------------------

+ Commands output for Initial rapid move

+---------------------------------------------------

begin INITIAL_RAPID_MOVE

"[N] G53 Z0"
"[N] G0[X][Y]"
"[N] G0[Z]"

+---------------------------------------------------
+  Commands output for rapid moves
+---------------------------------------------------

begin RAPID_MOVE

"[N] G0[X][Y][Z]"

+---------------------------------------------------
+  Commands output for feed rate moves
+---------------------------------------------------

begin FEED_MOVE

"[N] G1[X][Y][Z][F]"



+---------------------------------------------------
+  Commands output for the first clockwise arc move
+---------------------------------------------------

begin FIRST_CW_ARC_MOVE

"[N] G2[X][Y][I][J][F]"

+---------------------------------------------------
+  Commands output for clockwise arc  move
+---------------------------------------------------

begin CW_ARC_MOVE

"[N] G2[X][Y][I][J]"

+---------------------------------------------------
+  Commands output for the first counterclockwise arc move
+---------------------------------------------------

begin FIRST_CCW_ARC_MOVE

"[N] G3[X][Y][I][J][F]"

+---------------------------------------------------
+  Commands output for counterclockwise arc  move
+---------------------------------------------------

begin CCW_ARC_MOVE

"[N] G3[X][Y][I][J]"

begin JET_TOOL_ON
+---------------------------------------------------
+ Commands output when the cutter's power is turned ON
+---------------------------------------------------

";Jet Tool On"
";no command needed"

begin JET_TOOL_POWER
+---------------------------------------------------
+ Commands output when the cutter's power is set
+---------------------------------------------------

";Jet tool power"
"S[P]"

begin JET_TOOL_OFF
+---------------------------------------------------
+ Commands output when the cutter's power is turned OFF
+---------------------------------------------------

"S0"

+---------------------------------------------
+  Commands output for a dwell move
+---------------------------------------------

begin DWELL_MOVE

"G04 [DWELL]"

+---------------------------------------------------
+  Commands output at toolchange
+---------------------------------------------------

begin TOOLCHANGE

"[N] ; ---------------------------------------------"
"[N] ; Toolchange: T[T] - Speed:[S]"
"[N] ; ---------------------------------------------"
"[N] ; Start Tool Change"
"[N] T[T] M6"
"[N] G43 H[T]"
"[N] ; Spindle on CW"
"[N] M3 [S][F]"
"[N] ; ---------------------------------------------"

+---------------------------------------------------
+  Commands output at the end of the file
+---------------------------------------------------

begin FOOTER

"[N] ; ---------------------------------------------"
"[N] G53 Z0"
"[N] ; Spindle off"
"[N] M5"
"[N] ; Coolant Off"
"[N] M9"
"[N] ; Canned Cycle Cancel"
"[N] G80"
"[N] ; End-Custom M Code"
"[N] M30"
